Repository XenitAB/terraform-modules, pull requests merged in 2021-05, with the labels that each got.

#256 Add group and permissions for ACR reader
  modules/azure/aks-global/README.md
  modules/azure/aks-global/acr.tf
  modules/azure/governance-global/README.md
  modules/azure/governance-global/delegate-acr.tf
Labels: enhancement

#259 linkerd module
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/ingress-healthz/README.md
  modules/kubernetes/ingress-healthz/main.tf
  modules/kubernetes/ingress-healthz/templates/values.yaml.tpl
  modules/kubernetes/ingress-healthz/variables.tf
  modules/kubernetes/ingress-nginx/README.md
  modules/kubernetes/ingress-nginx/main.tf
  modules/kubernetes/ingress-nginx/templates/values.yaml.tpl
  modules/kubernetes/ingress-nginx/variables.tf
  modules/kubernetes/linkerd/README.md
  modules/kubernetes/linkerd/charts/linkerd-extras/.helmignore
  modules/kubernetes/linkerd/charts/linkerd-extras/Chart.yaml
  modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-identity-issuer.yaml
  modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-proxy-injector.yaml
  modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-sp-validator.yaml
  modules/kubernetes/linkerd/charts/linkerd-extras/templates/linkerd-trust-anchor.yaml
  modules/kubernetes/linkerd/charts/linkerd-extras/templates/webhook-issuer.yaml
  modules/kubernetes/linkerd/charts/linkerd-extras/values.yaml
  modules/kubernetes/linkerd/main.tf
  modules/kubernetes/linkerd/outputs.tf
  modules/kubernetes/linkerd/templates/values-cni.yaml.tpl
  modules/kubernetes/linkerd/templates/values.yaml.tpl
  modules/kubernetes/linkerd/variables.tf
  validation/kubernetes/linkerd/main.tf
Labels: enhancement

#272 Rollback to aad-pod-identity 4.0.0 (v1.7.5)
  modules/kubernetes/aad-pod-identity/main.tf
Labels: bug

#274 Run make validate in paralell
  Makefile
Labels: enhancement

#284 Typo (learning the ropes of the repo)
  modules/azure/aks-global/README.md
  modules/azure/aks-global/variables.tf
  modules/azure/aks/README.md
  modules/azure/aks/variables.tf
  modules/azure/azure-pipelines-agent-vmss/README.md
  modules/azure/azure-pipelines-agent-vmss/variables.tf
  modules/azure/core/README.md
  modules/azure/core/variables.tf
  modules/azure/github-runner/README.md
  modules/azure/github-runner/variables.tf
  modules/azure/governance-global/README.md
  modules/azure/governance-global/variables.tf
  modules/azure/governance-regional/README.md
  modules/azure/governance-regional/variables.tf
  modules/azure/governance/README.md
  modules/azure/governance/variables.tf
  modules/azure/hub/README.md
  modules/azure/hub/variables.tf
Labels: documentation
