Repository XenitAB/terraform-modules, pull requests merged in 2024-11, with the labels that each got.

#1235 feat: add support for karpenter autoscaling
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/karpenter/README.md
  modules/kubernetes/karpenter/main.tf
  modules/kubernetes/karpenter/outputs.tf
  modules/kubernetes/karpenter/templates/node-classes.yaml.tpl
  modules/kubernetes/karpenter/templates/node-pools.yaml.tpl
  modules/kubernetes/karpenter/templates/secret.yaml.tpl
  modules/kubernetes/karpenter/templates/values.yaml.tpl
  modules/kubernetes/karpenter/variables.tf
  modules/kubernetes/karpenter/workload_identity.tf
  validation/kubernetes/karpenter/main.tf
Labels: feature

#1237 refactor: associate AKS default NSG with vnet subnet
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
Labels: refactor

#1239 feat: add support for popeye k8s linter
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/popeye/README.md
  modules/kubernetes/popeye/charts/popeye/.helmignore
  modules/kubernetes/popeye/charts/popeye/Chart.yaml
  modules/kubernetes/popeye/charts/popeye/templates/cluster-role-binding.yaml
  modules/kubernetes/popeye/charts/popeye/templates/cluster-role.yaml
  modules/kubernetes/popeye/charts/popeye/templates/config-map.yaml
  modules/kubernetes/popeye/charts/popeye/templates/cronjob.yaml
  modules/kubernetes/popeye/charts/popeye/templates/pvc.yaml
  modules/kubernetes/popeye/charts/popeye/templates/secret.yaml
  modules/kubernetes/popeye/charts/popeye/templates/service-account.yaml
  modules/kubernetes/popeye/charts/popeye/templates/storage-class.yaml
  modules/kubernetes/popeye/charts/popeye/values.yaml.tpl
  modules/kubernetes/popeye/main.tf
  modules/kubernetes/popeye/outputs.tf
  modules/kubernetes/popeye/variables.tf
  modules/kubernetes/popeye/workload-identity.tf
  validation/kubernetes/popeye/main.tf
Labels: feature

#1244 fix: add required name label to ingress-nginx namespace
  modules/kubernetes/ingress-nginx/main.tf
Labels: fix

#1246 fix: ignore metadata changes for flux namespace
  modules/kubernetes/fluxcd/main.tf
Labels: fix

#1248 feat: add support for specifying parameters for additional storage classes
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/storage-class.tf
  modules/kubernetes/aks-core/variables.tf
Labels: feature

#1236 feat: add envoy gateway
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/azure-policy/README.md
  modules/kubernetes/azure-policy/locals.tf
  modules/kubernetes/azure-policy/main.tf
  modules/kubernetes/azure-policy/templates/envoy_gateway_require_tls.yaml.tpl
  modules/kubernetes/azure-policy/variables.tf
  modules/kubernetes/envoy-gateway/README.md
  modules/kubernetes/envoy-gateway/main.tf
  modules/kubernetes/envoy-gateway/outputs.tf
  modules/kubernetes/envoy-gateway/templates/envoy-gateway.yaml.tpl
  modules/kubernetes/envoy-gateway/templates/kustomization.yaml.tpl
  modules/kubernetes/envoy-gateway/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/envoy-gateway/main.tf
Labels: feature

#1251 feat: Add option to set NSG rules
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/nsg.tf
  modules/azure/aks/variables.tf
  modules/azure/core/README.md
  modules/azure/core/locals.tf
  modules/azure/core/nsg.tf
  modules/azure/core/subnets.tf
  modules/azure/core/variables.tf
  validation/azure/aks/main.tf
  validation/azure/core/main.tf
Labels: feature

#1257 chore: bumping kubectl provider version
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/helm-crd-oci/README.md
  modules/kubernetes/helm-crd-oci/main.tf
  modules/kubernetes/helm-crd/README.md
  modules/kubernetes/helm-crd/main.tf
  modules/kubernetes/karpenter/README.md
  modules/kubernetes/karpenter/main.tf
Labels: chore

#1258 fix: defender-shenanigans
  modules/azure/aks/defender.tf
Labels: fix

#1224 refactor: remove azad-kube-proxy module
  modules/azure-ad/azad-kube-proxy/README.md
  modules/azure-ad/azad-kube-proxy/main.tf
  modules/azure-ad/azad-kube-proxy/outputs.tf
  modules/azure-ad/azad-kube-proxy/variables.tf
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/azad-kube-proxy/README.md
  modules/kubernetes/azad-kube-proxy/main.tf
  modules/kubernetes/azad-kube-proxy/outputs.tf
  modules/kubernetes/azad-kube-proxy/templates/azad-kube-proxy.yaml.tpl
  modules/kubernetes/azad-kube-proxy/templates/azure-config.yaml.tpl
  modules/kubernetes/azad-kube-proxy/templates/kustomization.yaml.tpl
  modules/kubernetes/azad-kube-proxy/variables.tf
  modules/kubernetes/azad-kube-proxy/workload-identity.tf
  validation/azure-ad/azad-kube-proxy/main.tf
  validation/kubernetes/azad-kube-proxy/main.tf
Labels: refactor
