Repository XenitAB/terraform-modules, pull requests merged in 2024-10, with the labels that each got.

#1193 ci: bump terraform-docs version to v 0.19.0
  .github/workflows/check.yaml
Labels: ci/cd

#1192 feat: improved grafana agent configuration
  modules/azure/aks-regional/README.md
  modules/azure/aks/README.md
  modules/azure/azure-pipelines-agent-vmss/README.md
  modules/azure/core/README.md
  modules/azure/github-runner/README.md
  modules/azure/governance-global/README.md
  modules/azure/governance-regional/README.md
  modules/azure/hub/README.md
  modules/azure/names/README.md
  modules/azure/xkf-governance-global-data/README.md
  modules/azure/xkf-governance-global/README.md
  modules/kubernetes/aad-pod-identity/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/azad-kube-proxy/README.md
  modules/kubernetes/azure-policy/README.md
  modules/kubernetes/azure-service-operator/README.md
  modules/kubernetes/control-plane-logs/README.md
  modules/kubernetes/datadog/README.md
  modules/kubernetes/external-dns/README.md
  modules/kubernetes/fluxcd-v2-azdo/README.md
  modules/kubernetes/fluxcd-v2-github/README.md
  modules/kubernetes/grafana-agent/README.md
  modules/kubernetes/grafana-agent/main.tf
  modules/kubernetes/grafana-agent/templates/grafana-agent-extras.yaml.tpl
  modules/kubernetes/grafana-agent/templates/kustomization.yaml.tpl
  modules/kubernetes/grafana-agent/variables.tf
  modules/kubernetes/grafana-alloy/README.md
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/ingress-nginx/README.md
  modules/kubernetes/prometheus/README.md
  modules/kubernetes/promtail/README.md
  modules/kubernetes/telepresence/README.md
  modules/kubernetes/velero/README.md
Labels: feature

#1191 chore: Update Ingress-nginx, Cert-manager and external-dns
  modules/kubernetes/cert-manager/templates/cert-manager.yaml.tpl
  modules/kubernetes/external-dns/templates/external-dns.yaml.tpl
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
Labels: chore

#1196 feat: Move azad-kube-proxy to aks-core and use SecretProviderClass
  modules/azure/aks-regional/README.md
  modules/azure/aks-regional/azad-kube-proxy.tf
  modules/azure/aks-regional/outputs.tf
  modules/azure/aks-regional/variables.tf
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/azad-kube-proxy/README.md
  modules/kubernetes/azad-kube-proxy/main.tf
  modules/kubernetes/azad-kube-proxy/templates/azad-kube-proxy.yaml.tpl
  modules/kubernetes/azad-kube-proxy/templates/azure-config.yaml.tpl
  modules/kubernetes/azad-kube-proxy/variables.tf
  modules/kubernetes/azad-kube-proxy/workload-identity.tf
  validation/kubernetes/azad-kube-proxy/main.tf
Labels: feature

#1197 fix: dont install unused CRDs
  modules/kubernetes/aks-core/modules.tf
Labels: fix

#1200 feat: metrics for flux system
  LOCAL_DEVELOPMENT.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/grafana-alloy/README.md
  modules/kubernetes/grafana-alloy/templates/grafana-alloy-controller.yaml.tpl
  modules/kubernetes/grafana-alloy/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/grafana-alloy/main.tf
Labels: feature

#1202 fix: some tenants don't have gatekeeper installed/enabled
  modules/kubernetes/grafana-alloy/templates/kustomization.yaml.tpl
Labels: fix

#1203 chore!: bump flux provider to v1.4.0
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/fluxcd-v2-azdo/README.md
  modules/kubernetes/fluxcd-v2-azdo/main.tf
  modules/kubernetes/fluxcd-v2-azdo/templates/flux-alerts.yaml.tpl
  modules/kubernetes/fluxcd-v2-azdo/templates/git-auth-proxy-values.yaml.tpl
  modules/kubernetes/fluxcd-v2-azdo/templates/kustomization-override.yaml
  modules/kubernetes/fluxcd-v2-azdo/templates/kustomization.yaml.tpl
  modules/kubernetes/fluxcd-v2-azdo/templates/tenant.yaml
  modules/kubernetes/fluxcd-v2-azdo/variables.tf
  modules/kubernetes/fluxcd-v2-github/README.md
  modules/kubernetes/fluxcd-v2-github/main.tf
  modules/kubernetes/fluxcd-v2-github/outputs.tf
  modules/kubernetes/fluxcd-v2-github/templates/cluster-tenants.yaml
  modules/kubernetes/fluxcd-v2-github/templates/flux-alerts.yaml.tpl
  modules/kubernetes/fluxcd-v2-github/templates/git-auth-proxy-values.yaml.tpl
  modules/kubernetes/fluxcd-v2-github/templates/kustomization-override.yaml
  modules/kubernetes/fluxcd-v2-github/templates/kustomization.yaml.tpl
  modules/kubernetes/fluxcd-v2-github/variables.tf
  modules/kubernetes/fluxcd/README.md
  modules/kubernetes/fluxcd/main.tf
  modules/kubernetes/fluxcd/outputs.tf
  modules/kubernetes/fluxcd/templates/cluster-tenants.yaml
  modules/kubernetes/fluxcd/templates/git-auth-proxy-values.yaml.tpl
  modules/kubernetes/fluxcd/templates/kustomization-override.yaml.tpl
  modules/kubernetes/fluxcd/templates/tenant.yaml
  modules/kubernetes/fluxcd/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/fluxcd-v2-azdo/main.tf
  validation/kubernetes/fluxcd-v2-github/main.tf
  validation/kubernetes/fluxcd/main.tf
Labels: chore, breaking change

#1206 fix: create azure policy regardless of flux config
  modules/kubernetes/aks-core/modules.tf
Labels: fix

#1207 fix: don't create flux tenant artifacts if flux isn't enabled
  modules/kubernetes/fluxcd/main.tf
Labels: fix

#1208 fix: don't create secret for git-auth-proxy if tenant is not using flux
  modules/kubernetes/fluxcd/main.tf
Labels: fix

#1209 fix: flux project name is null for GitHub tenants
  modules/kubernetes/fluxcd/main.tf
Labels: fix

#1211 fix: wrong GitHub application id attribute provided in template
  modules/kubernetes/fluxcd/templates/git-auth-proxy-values.yaml.tpl
Labels: fix

#1213 fix: glux bootstrap not working for GitHub tenants
  modules/kubernetes/fluxcd/main.tf
Labels: fix

#1214 fix: base64 encode private key for flux GitHub tenants
  modules/kubernetes/fluxcd/main.tf
  modules/kubernetes/fluxcd/templates/git-auth-proxy-values.yaml.tpl
Labels: fix

#1216 fix: add end_date to azad-proxy azuread_application_password
  modules/azure-ad/azad-kube-proxy/main.tf
Labels: fix

#1219 fix: adding namespaced discovery
  modules/kubernetes/grafana-alloy/templates/grafana-alloy-controller.yaml.tpl
Labels: fix

#1220 fix: add flux notification-controller
  modules/kubernetes/fluxcd/main.tf
  modules/kubernetes/fluxcd/templates/kustomization-override.yaml.tpl
Labels: fix

#1222 fix: add flux notification provider
  modules/kubernetes/fluxcd/templates/tenant.yaml
Labels: fix

#1217 fix: Add reloader annotation to azad-kube-proxy
  modules/kubernetes/azad-kube-proxy/templates/azad-kube-proxy.yaml.tpl
  modules/kubernetes/azad-kube-proxy/templates/azure-config.yaml.tpl
Labels: fix

#1226 feat: add support for Gateway API
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/cert-manager/README.md
  modules/kubernetes/cert-manager/main.tf
  modules/kubernetes/cert-manager/templates/cert-manager.yaml.tpl
  modules/kubernetes/cert-manager/variables.tf
  modules/kubernetes/external-dns/README.md
  modules/kubernetes/external-dns/main.tf
  modules/kubernetes/external-dns/templates/external-dns.yaml.tpl
  modules/kubernetes/external-dns/variables.tf
  modules/kubernetes/gateway-api/README.md
  modules/kubernetes/gateway-api/main.tf
  modules/kubernetes/gateway-api/outputs.tf
  modules/kubernetes/gateway-api/templates/kustomization.yaml.tpl
  modules/kubernetes/gateway-api/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/cert-manager/main.tf
  validation/kubernetes/external-dns/main.tf
  validation/kubernetes/gateway-api/main.tf
Labels: feature

#1227 chore: update cert-manager CRDs to v1.15.3
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/helm-crd/main.tf
Labels: chore

#1228 feat: add support for Nginx Gateway Fabric
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/nginx-gateway-fabric/README.md
  modules/kubernetes/nginx-gateway-fabric/main.tf
  modules/kubernetes/nginx-gateway-fabric/outputs.tf
  modules/kubernetes/nginx-gateway-fabric/templates/gateway-fabric.yaml.tpl
  modules/kubernetes/nginx-gateway-fabric/templates/kustomization.yaml.tpl
  modules/kubernetes/nginx-gateway-fabric/variables.tf
  validation/kubernetes/nginx-gateway-fabric/main.tf
Labels: feature

#1230 chore: Upgrade Azurerm to 4.7.0
  modules/azure/aks-global/README.md
  modules/azure/aks-global/main.tf
  modules/azure/aks-regional/README.md
  modules/azure/aks-regional/main.tf
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/main.tf
  modules/azure/azure-pipelines-agent-vmss/README.md
  modules/azure/azure-pipelines-agent-vmss/main.tf
  modules/azure/core/README.md
  modules/azure/core/log.tf
  modules/azure/core/main.tf
  modules/azure/core/routes.tf
  modules/azure/core/subnets.tf
  modules/azure/github-runner/README.md
  modules/azure/github-runner/main.tf
  modules/azure/governance-global/README.md
  modules/azure/governance-global/main.tf
  modules/azure/governance-regional/README.md
  modules/azure/governance-regional/main.tf
  modules/azure/hub/README.md
  modules/azure/hub/main.tf
  modules/azure/xkf-governance-global-data/README.md
  modules/azure/xkf-governance-global-data/main.tf
  modules/azure/xkf-governance-global/README.md
  modules/azure/xkf-governance-global/main.tf
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/azad-kube-proxy/README.md
  modules/kubernetes/azad-kube-proxy/main.tf
  modules/kubernetes/azure-metrics/README.md
  modules/kubernetes/azure-metrics/main.tf
  modules/kubernetes/azure-policy/README.md
  modules/kubernetes/azure-policy/main.tf
  modules/kubernetes/azure-service-operator/README.md
  modules/kubernetes/azure-service-operator/main.tf
  modules/kubernetes/cert-manager/README.md
  modules/kubernetes/cert-manager/main.tf
  modules/kubernetes/control-plane-logs/README.md
  modules/kubernetes/control-plane-logs/main.tf
  modules/kubernetes/datadog/README.md
  modules/kubernetes/datadog/main.tf
  modules/kubernetes/external-dns/README.md
  modules/kubernetes/external-dns/main.tf
  modules/kubernetes/grafana-alloy/README.md
  modules/kubernetes/grafana-alloy/main.tf
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/grafana-k8s-monitoring/main.tf
  modules/kubernetes/prometheus/README.md
  modules/kubernetes/prometheus/main.tf
  modules/kubernetes/promtail/README.md
  modules/kubernetes/promtail/main.tf
  modules/kubernetes/trivy/README.md
  modules/kubernetes/trivy/main.tf
  modules/kubernetes/velero/README.md
  modules/kubernetes/velero/main.tf
  validation/kubernetes/trivy/tf.log
Labels: chore

#1231 feat: Upgrade Linkerd-CNI and CRDs
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/linkerd/main.tf
Labels: feature

#1234 chore: Upgrade azad-kube-proxy to 0.0.48
  modules/kubernetes/azad-kube-proxy/templates/azad-kube-proxy.yaml.tpl
Labels: chore
