Repository XenitAB/terraform-modules, pull requests merged in 2024-06, with the labels that each got.

#1122 chore: bump azurerm provider to v3.107.0
  CHANGELOG.md
  modules/azure/aks-global/README.md
  modules/azure/aks-global/main.tf
  modules/azure/aks-regional/README.md
  modules/azure/aks-regional/main.tf
  modules/azure/aks/README.md
  modules/azure/aks/main.tf
  modules/azure/azure-pipelines-agent-vmss/README.md
  modules/azure/azure-pipelines-agent-vmss/main.tf
  modules/azure/core/README.md
  modules/azure/core/main.tf
  modules/azure/github-runner/README.md
  modules/azure/github-runner/main.tf
  modules/azure/governance-global/README.md
  modules/azure/governance-global/main.tf
  modules/azure/governance-regional/README.md
  modules/azure/governance-regional/main.tf
  modules/azure/hub/README.md
  modules/azure/hub/main.tf
  modules/azure/xkf-governance-global-data/README.md
  modules/azure/xkf-governance-global-data/main.tf
  modules/azure/xkf-governance-global/README.md
  modules/azure/xkf-governance-global/main.tf
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/azure-metrics/README.md
  modules/kubernetes/azure-metrics/main.tf
  modules/kubernetes/azure-policy/README.md
  modules/kubernetes/azure-policy/main.tf
  modules/kubernetes/cert-manager/README.md
  modules/kubernetes/cert-manager/main.tf
  modules/kubernetes/control-plane-logs/README.md
  modules/kubernetes/control-plane-logs/main.tf
  modules/kubernetes/datadog/README.md
  modules/kubernetes/datadog/main.tf
  modules/kubernetes/external-dns/README.md
  modules/kubernetes/external-dns/main.tf
  modules/kubernetes/prometheus/README.md
  modules/kubernetes/prometheus/main.tf
  modules/kubernetes/promtail/README.md
  modules/kubernetes/promtail/main.tf
  modules/kubernetes/trivy/README.md
  modules/kubernetes/trivy/main.tf
  modules/kubernetes/velero/README.md
  modules/kubernetes/velero/main.tf
  validation/kubernetes/trivy/tf.log
Labels: chore

#1120 feat: add support for starting/stopping a cluster using Azure automation
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/automation/main.tf
  modules/azure/aks/automation/scripts/aks-start-stop-scale.ps1.tpl
  modules/azure/aks/automation/variables.tf
  modules/azure/aks/modules.tf
  modules/azure/aks/variables.tf
Labels: feature

#1126 feat: add support for AKS cost analysis
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/variables.tf
Labels: feature

#1128 fix: allow vector to use writable root file system
  modules/kubernetes/azure-policy/main.tf
Labels: fix

#1129 ci: don't include update of CHANGELOG in the CHANGELOG
  xenit-changelog.toml
Labels: ci/cd

#1131 ci: run check when PR is labeled
  .github/workflows/check.yaml
Labels: ci/cd

#1132 chore: bump peter-evans/create-pull-request to v6
  .github/workflows/changelog.yaml
Labels: chore

#1134 chore: update spegel to 0.0.23
  modules/kubernetes/spegel/templates/spegel.yaml.tpl
Labels: chore

#1136 feat: make upgrade_settings configurable
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/variables.tf
Labels: feature

#1140 refactor: update of the default log retention time for azure to 30 days
  modules/azure/aks/README.md
  modules/azure/aks/variables.tf
Labels: refactor
