Repository XenitAB/terraform-modules, pull requests merged in 2024-09, with the labels that each got.

#1167 feat: add initial support for automation alerts
  modules/azure/aks/README.md
  modules/azure/aks/automation/main.tf
  modules/azure/aks/automation/variables.tf
  modules/azure/aks/modules.tf
  modules/azure/aks/variables.tf
Labels: feature

#1168 refactor: explicitly set AKS SKU tier and node count
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/variables.tf
  validation/azure/aks/main.tf
Labels: refactor

#1170 fix: incorrect naming of input variable
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/variables.tf
  validation/azure/aks/main.tf
Labels: fix

#1166 feat: adding filtering for namespaces for grafana k8s chart
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
  modules/kubernetes/grafana-k8s-monitoring/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/grafana-k8s-monitoring/main.tf
Labels: feature

#1173 chore: upgrade falco-exporter chart to 0.12.1
  modules/kubernetes/falco/templates/falco-exporter.yaml.tpl
Labels: chore

#1174 feat: disabling opencost
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
Labels: feature

#1175 fix: in some clusters we dont use gatekeeper-config
  modules/kubernetes/grafana-k8s-monitoring/templates/kustomization.yaml.tpl
Labels: fix

#1177 refactor: use Microsoft provider for Azure DevOps
  modules/kubernetes/fluxcd-v2-azdo/README.md
  modules/kubernetes/fluxcd-v2-azdo/main.tf
Labels: refactor

#1179 fix: wrong location name forces replacement of automation resources
  modules/azure/aks/README.md
  modules/azure/aks/automation/main.tf
  modules/azure/aks/automation/variables.tf
  modules/azure/aks/modules.tf
  modules/azure/aks/variables.tf
Labels: fix

#1180 feat: fixing the memory consumption issues
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
Labels: feature

#1182 feat: adding alerting for flux
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/fluxcd-v2-azdo/README.md
  modules/kubernetes/fluxcd-v2-azdo/main.tf
  modules/kubernetes/fluxcd-v2-azdo/templates/flux-alerts.yaml.tpl
  modules/kubernetes/fluxcd-v2-azdo/templates/kustomization.yaml.tpl
  modules/kubernetes/fluxcd-v2-azdo/variables.tf
  modules/kubernetes/fluxcd-v2-github/README.md
  modules/kubernetes/fluxcd-v2-github/main.tf
  modules/kubernetes/fluxcd-v2-github/templates/flux-alerts.yaml.tpl
  modules/kubernetes/fluxcd-v2-github/templates/kustomization.yaml.tpl
  modules/kubernetes/fluxcd-v2-github/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/fluxcd-v2-azdo/main.tf
  validation/kubernetes/fluxcd-v2-github/main.tf
Labels: feature

#1184 feat: changing the alerts interval evaluation time
  modules/kubernetes/fluxcd-v2-azdo/templates/kustomization-override.yaml
  modules/kubernetes/fluxcd-v2-github/templates/kustomization-override.yaml
Labels: feature

#1185 fix: Exclude ambassador namespace
  modules/kubernetes/aks-core/modules.tf
Labels: fix

#1186 fix: Revert Exclude ambassador namespace"
  modules/kubernetes/aks-core/modules.tf
Labels: fix

#1187 fix: telepresence deployment error
  modules/kubernetes/azure-policy/main.tf
  modules/kubernetes/gatekeeper/templates/gatekeeper-config.yaml.tpl
  modules/kubernetes/telepresence/templates/telepresence.yaml.tpl
Labels: fix

#1188 fix: grafana alloy using wrong location short name
  modules/kubernetes/aks-core/modules.tf
Labels: fix

#1189 feat: add gateway_transit option to peering_config
  modules/azure/hub/README.md
  modules/azure/hub/main.tf
  modules/azure/hub/variables.tf
Labels: feature
