Repository XenitAB/terraform-modules, pull requests merged in 2025-03, with the labels that each got.

#1314 fix: consolidation attempt rework
  modules/kubernetes/grafana-k8s-monitoring/main.tf
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
  modules/kubernetes/grafana-k8s-monitoring/templates/kustomization.yaml.tpl
Labels: fix

#1317 chore: upgrade nginx controller to latest version
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
Labels: chore

#1318 feat: add delegations block to subnet
  modules/azure/core/README.md
  modules/azure/core/locals.tf
  modules/azure/core/subnets.tf
  modules/azure/core/variables.tf
Labels: feature

#1319 feat: add support for nsg rule destination/source_address_prefixes
  modules/azure/core/README.md
  modules/azure/core/locals.tf
  modules/azure/core/nsg.tf
  modules/azure/core/variables.tf
Labels: feature
