Repository XenitAB/terraform-modules, pull requests merged in 2025-05, with the labels that each got.

#1334 feat: make it possible to enable ACR admin account
  modules/azure/aks-global/README.md
  modules/azure/aks-global/acr.tf
  modules/azure/aks-global/variables.tf
Labels: feature

#1335 feat: giving flux acr permissions
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/fluxcd/README.md
  modules/kubernetes/fluxcd/main.tf
  modules/kubernetes/fluxcd/templates/kustomization-override.yaml.tpl
  modules/kubernetes/fluxcd/variables.tf
  modules/kubernetes/fluxcd/workload-identity.tf
  validation/kubernetes/fluxcd/main.tf
Labels: feature

#1340 fix: broken grafana-k8s-monitoring template
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
Labels: fix

#1341 fix: linkerd template indentation and gatekeeper exclusion
  modules/kubernetes/aks-core/locals.tf
  modules/kubernetes/linkerd/main.tf
Labels: fix

#1342 fix: add grafana-k8s-monitoring as a gatekeeper excluded namespace
  modules/kubernetes/aks-core/locals.tf
Labels: fix

#1344 feat: enable tuning of vital ArgoCD parameters
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/argocd/README.md
  modules/kubernetes/argocd/main.tf
  modules/kubernetes/argocd/templates/argocd-values.yaml.tpl
  modules/kubernetes/argocd/variables.tf
Labels: feature

#1345 chore: upgrade argocd chart to 8.0.6
  modules/kubernetes/argocd/main.tf
  modules/kubernetes/argocd/templates/argocd-values.yaml.tpl
Labels: chore

#1347 feat: enable argocd metrics
  modules/kubernetes/argocd/templates/argocd-values.yaml.tpl
Labels: feature

#1348 fix: linkerd chart indentation errors
  modules/kubernetes/linkerd/main.tf
Labels: fix

#1350 feat: separate subnets per node pool
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/locals.tf
  modules/azure/aks/variables.tf
Labels: feature

#1352 chore: upgrade karpenter to 1.4.0
  modules/kubernetes/karpenter/main.tf
  modules/kubernetes/karpenter/templates/node-classes.yaml.tpl
Labels: chore
