Repository XenitAB/terraform-modules, pull requests merged in 2025-02, with the labels that each got.

#1279 feat: make ingress-nginx replicas configurable
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/ingress-nginx/README.md
  modules/kubernetes/ingress-nginx/main.tf
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
  modules/kubernetes/ingress-nginx/variables.tf
  validation/kubernetes/ingress-nginx/main.tf
Labels: feature

#1280 feat: allow scheduling ingress-nginx on spot nodes
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
Labels: feature

#1281 feat: allow cert-manager to run on spot nodes
  modules/kubernetes/cert-manager/templates/cert-manager.yaml.tpl
Labels: feature

#1283 chore: upgrading grafana k8s monitoring chart
  modules/azure-ad/.tflint.hcl
  modules/azure/.tflint.hcl
  modules/kubernetes/.tflint.hcl
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
  modules/kubernetes/grafana-k8s-monitoring/variables.tf
  modules/kubernetes/grafana-k8s-monitoring/workload-identity.tf
  validation/kubernetes/grafana-k8s-monitoring/main.tf
Labels: chore

#1286 fix: bad parsing of list
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/grafana-k8s-monitoring/main.tf
  modules/kubernetes/grafana-k8s-monitoring/templates/grafana-k8s-monitoring.yaml.tpl
  modules/kubernetes/grafana-k8s-monitoring/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/grafana-k8s-monitoring/main.tf
Labels: fix

#1287 fix: flux wrongful use of include_tenant_name
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/fluxcd/README.md
  modules/kubernetes/fluxcd/main.tf
  modules/kubernetes/fluxcd/templates/tenant.yaml
  modules/kubernetes/fluxcd/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/fluxcd/main.tf
Labels: fix

#1288 feat: adding support for ECK
  modules/kubernetes/README.md
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/eck-operator/README.md
  modules/kubernetes/eck-operator/main.tf
  modules/kubernetes/eck-operator/outputs.tf
  modules/kubernetes/eck-operator/templates/eck-operator.yaml.tpl
  modules/kubernetes/eck-operator/templates/kustomization.yaml.tpl
  modules/kubernetes/eck-operator/variables.tf
  validation/kubernetes/eck-operator/main.tf
Labels: feature

#1289 fix: bad copy pasta
  modules/kubernetes/eck-operator/main.tf
Labels: fix

#1293 fix: add required network contributor role at subscription level
  modules/azure/aks/README.md
  modules/azure/aks/aad-group.tf
  modules/azure/aks/main.tf
Labels: fix

#1295 feat: upgrade Karpenter and enable spotToSpotConsolidation
  modules/kubernetes/karpenter/main.tf
  modules/kubernetes/karpenter/templates/values.yaml.tpl
Labels: feature

#1296 fix: make network contributor role work with cilium
  modules/azure/aks/aad-group.tf
Labels: fix

#1297 fix: aks validation should allow no nodepools elements
  modules/azure/aks/variables.tf
  validation/azure/aks/main.tf
Labels: fix

#1299 chore: bump azurerm provider to v 4.19.0
  modules/azure/aks-global/README.md
  modules/azure/aks-global/main.tf
  modules/azure/aks-regional/README.md
  modules/azure/aks-regional/main.tf
  modules/azure/aks/README.md
  modules/azure/aks/main.tf
  modules/azure/azure-pipelines-agent-vmss/README.md
  modules/azure/azure-pipelines-agent-vmss/main.tf
  modules/azure/core/README.md
  modules/azure/core/main.tf
  modules/azure/github-runner/README.md
  modules/azure/github-runner/main.tf
  modules/azure/governance-global/README.md
  modules/azure/governance-global/main.tf
  modules/azure/governance-regional/README.md
  modules/azure/governance-regional/main.tf
  modules/azure/hub/README.md
  modules/azure/hub/main.tf
  modules/azure/xkf-governance-global-data/README.md
  modules/azure/xkf-governance-global-data/main.tf
  modules/azure/xkf-governance-global/README.md
  modules/azure/xkf-governance-global/main.tf
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/main.tf
  modules/kubernetes/azure-metrics/README.md
  modules/kubernetes/azure-metrics/main.tf
  modules/kubernetes/azure-policy/README.md
  modules/kubernetes/azure-policy/main.tf
  modules/kubernetes/azure-service-operator/README.md
  modules/kubernetes/azure-service-operator/main.tf
  modules/kubernetes/cert-manager/README.md
  modules/kubernetes/cert-manager/main.tf
  modules/kubernetes/control-plane-logs/README.md
  modules/kubernetes/control-plane-logs/main.tf
  modules/kubernetes/datadog/README.md
  modules/kubernetes/datadog/main.tf
  modules/kubernetes/eck-operator/README.md
  modules/kubernetes/eck-operator/main.tf
  modules/kubernetes/external-dns/README.md
  modules/kubernetes/external-dns/main.tf
  modules/kubernetes/grafana-alloy/README.md
  modules/kubernetes/grafana-alloy/main.tf
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/grafana-k8s-monitoring/main.tf
  modules/kubernetes/karpenter/README.md
  modules/kubernetes/karpenter/main.tf
  modules/kubernetes/litmus/README.md
  modules/kubernetes/litmus/main.tf
  modules/kubernetes/popeye/README.md
  modules/kubernetes/popeye/main.tf
  modules/kubernetes/prometheus/README.md
  modules/kubernetes/prometheus/main.tf
  modules/kubernetes/promtail/README.md
  modules/kubernetes/promtail/main.tf
  modules/kubernetes/trivy/README.md
  modules/kubernetes/trivy/main.tf
  modules/kubernetes/velero/README.md
  modules/kubernetes/velero/main.tf
  validation/kubernetes/tf.log
  validation/kubernetes/trivy/tf.log
Labels: chore

#1300 fix: moving envoy out of azure-policy module
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/azure-policy/README.md
  modules/kubernetes/azure-policy/locals.tf
  modules/kubernetes/azure-policy/main.tf
  modules/kubernetes/azure-policy/variables.tf
  modules/kubernetes/envoy-gateway/README.md
  modules/kubernetes/envoy-gateway/locals.tf
  modules/kubernetes/envoy-gateway/main.tf
  modules/kubernetes/envoy-gateway/templates/envoy_gateway_require_tls.yaml.tpl
  modules/kubernetes/envoy-gateway/variables.tf
  validation/kubernetes/aks-core/main.tf
Labels: fix

#1302 feat: adding an ingress so we can easily alert for cluster health status
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/aks-core/variables.tf
  modules/kubernetes/ingress-nginx/README.md
  modules/kubernetes/ingress-nginx/main.tf
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
  modules/kubernetes/ingress-nginx/variables.tf
  validation/kubernetes/aks-core/main.tf
  validation/kubernetes/ingress-nginx/main.tf
Labels: feature

#1303 feat: add support for removing spot instances taints in clusters that are automated to start/stop
  modules/kubernetes/aks-core/README.md
  modules/kubernetes/aks-core/aks-core-extras.tf
  modules/kubernetes/aks-core/charts/aks-core-extras/templates/spot-instances-hack.yaml
  modules/kubernetes/aks-core/charts/aks-core-extras/values.yaml
  modules/kubernetes/aks-core/variables.tf
Labels: feature

#1304 feat: add support for KEDA autoscaling
  modules/azure/aks/README.md
  modules/azure/aks/aks.tf
  modules/azure/aks/variables.tf
Labels: feature

#1305 fix: only create nginx_ingress_healthz for public ingress
  modules/kubernetes/ingress-nginx/main.tf
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
Labels: fix

#1307 fix: nginx templating syntax
  modules/kubernetes/ingress-nginx/templates/ingress-nginx.yaml.tpl
Labels: fix

#1309 fix: flux monitoring for production clusters
  modules/kubernetes/fluxcd/templates/tenant.yaml
Labels: fix

#1310 fix: not a good solution when there are multiple tennats so instead w…
  modules/kubernetes/fluxcd/templates/cluster-tenants.yaml
  modules/kubernetes/fluxcd/templates/tenant.yaml
Labels: fix

#1311 chore: consolidating all monitoring resources to avoid CRD issues
  modules/kubernetes/aks-core/modules.tf
  modules/kubernetes/external-dns/templates/external-dns.yaml.tpl
  modules/kubernetes/fluxcd/templates/cluster-tenants.yaml
  modules/kubernetes/grafana-k8s-monitoring/README.md
  modules/kubernetes/grafana-k8s-monitoring/main.tf
  modules/kubernetes/grafana-k8s-monitoring/templates/monitors.yaml.tpl
  modules/kubernetes/grafana-k8s-monitoring/variables.tf
Labels: chore

#1312 fix: typo
  modules/kubernetes/grafana-k8s-monitoring/templates/monitors.yaml.tpl
Labels: fix
